import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { clerkMiddleware } from "@clerk/nextjs/server";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

const font = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

/*const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body>
        <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main className={`${font.variable} antialiased`}>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
