import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SocketProvider } from "@/components/providers/socket-provider";

const font = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

/*const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <main className={`${font.variable} antialiased`}>
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem storageKey="discord-theme">
                <SocketProvider>
                  <ModalProvider/>
                  {children}
                </SocketProvider>
              </ThemeProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}